### PR TITLE
Update header.html

### PR DESCRIPTION
**Pull request by 1265578519**
使用全球CDN，并且包含中国大陆的staticfile.org

### CODE REVIEW

**Comment by Jeroen52** [comment]
What is with the change in CDN?

**Comment by 1265578519** [comment]
@Jeroen52 用于节省用户前台访问产生的font流量

**Comment by Jeroen52** [comment]
I don't see why you'd want to save that.

I actively try to keep tracking to a minimum using this codebase, the only thing that I'm doing is scanning for computer virusses, if file encryption was built-in the code I'd even enable it.

**Comment by 1265578519** [comment]
@Jeroen52 你可以通过Chrome F12按键切换network进行网络抓包分析，每一次的页面访问，materialize它将浪费服务器500K传输流量（接近一张高清图片大小），如果你觉得这不算什么，，那我也没什么可说，如果页面访问量巨大，那么它需要昂达的服务器流量

**Comment by Jeroen52** [comment]
@1265578519 It is actually a good concern you have, bloat is not that good for websites and I have been looking carefully at the bloat that I leave behind myself as well.

Although the thing that kicks my nuggets is that it is a CDN that is hosted by a Chinese company, which is no offense to the Chinese people but instead somewhat political. Mainly because of the widespread internet censorship and website blocking in the Chinese Mainland.

What I would approve of is an opt-in kind of thing, where you have the choice of getting something a bit lighter.

**Comment by 1265578519** [comment]
@Jeroen52  
image
https://github.com/staticfile/static 我不是很懂英语，但是这staticfile CDN项目至少在github开源的，既然你觉得不好我就关闭了吧

**Pull request closed without merging**
