### PR TITLE
URL encode the returned filename

### PR DESCRIPTION
**Pull request by nixxquality**
There's a minor pain whenever you upload a file that has, say a space or a #, in the filename right now, as it's not directly usable in IM and the likes.

Pretty easy fix though.

Also, I took the liberty of fixing your opening <?php tag. Neku, you're too silly.

### CODE REVIEW

**Comment by nokonoko** [comment]
Ugh forgot to strip spaces when I rewrote, will fix when I get home.

**Comment by nokonoko** [comment]
No wait I do strip spaces and whitespace as well as tags, Nothing to fix.

**Comment by nixxquality** [comment]
Oh okay. Well, there's still the issue of files with # in the filename. This still solves that!

**Comment by nokonoko** [comment]
Goodie will apply on server in a few hours.

**Pull request merged**
