### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by alwaysontop617**

### CODE REVIEW

**Comment by alucard0134** [comment]
I would assume the maintainer is smart enough not to set their php error reporting to development, so I think this isn't too necessary

**Comment by pierre-alain-b** [comment]
Agreed this does not seem very much necessary.

**Comment by alucard0134** [comment]
@alwaysontop617 like no offence but learn how to contribute, seriously. I went thru your profile and all I see are the world's shittiest PR messages and commits. Like seriously I wanted to die and feel sorrow for those who had to review your crap @nokonoko pls review

**Comment by nokonoko** [comment]
No point in this tbh fam.

**Pull request closed without merging**
