### PR TITLE
fix upload path

### PR DESCRIPTION
**Pull request by Henrocker**

### CODE REVIEW

**Comment by avail** [comment]
/public is not meant to be in the url. ever. you point your vhost to /public

**Comment by Henrocker** [comment]
2 reasons why.

1. Config file only suggests to sperate upload and home url. I use one subdomain for both, hence, only with this fix downloading uploaded files works properly.
2. My public and files folders are both not indexable.

**Comment by avail** [comment]
The readme lists intended use for how the software is made, it's open source so if you want to run it in a different setting, you can modify it on your own. Why make a PR for this?

**Comment by Jeroen52** [comment]
Then use two subdomains.

**Comment by Jeroen52** [comment]
Your profile says that you're a "Web-TLS enthusiast", so am I.

And SNI has been a thing for many years, and Let's Encrypt has been publicly available for at least two years too.

**Comment by Henrocker** [comment]
Alright, got it. Thanks everyone for the hot and active discussion.

I am still using one subdomain for both situations and I think this might be helpful for people that do the same.

**Pull request closed without merging**
