### PR TITLE
Simply add a new line after an upload through APIs

### PR DESCRIPTION
**Pull request by sandvige**
image

### CODE REVIEW

**Comment by avail** [comment]
This is not good. Curl not adding a newline after executing shit is it's own fault.
Some applications will break if there's a newline present in the response.

**Comment by sandvige** [comment]
How about now @avail?

**Comment by alucard0134** [comment]
this is seriously why we cannot have nice things

**Comment by alucard0134** [comment]
private static function textSuccess($files)
    {
        $result = '';
        foreach ($files as $file) {
            $result .= $file['url']."\n";
        }
        return $result;
    }
this is how pomf/pomf did it and it just works

**Comment by sandvige** [comment]
File.io is doing the job much better than you :)

**Comment by alucard0134** [comment]
well file.io must be pretty retarded for accepting your PR

**Pull request closed without merging**
